<?php


 function autoload_6c629975753a482af019f5069dfbfd34($class)
{
    $classes = array(
        'Panopto\Session\SessionManagement' => __DIR__ .'/SessionManagement.php',
        'Panopto\Session\AuthenticationInfo' => __DIR__ .'/AuthenticationInfo.php',
        'Panopto\Session\SessionState' => __DIR__ .'/SessionState.php',
        'Panopto\Session\ListSessionsRequest' => __DIR__ .'/ListSessionsRequest.php',
        'Panopto\Session\Pagination' => __DIR__ .'/Pagination.php',
        'Panopto\Session\SessionSortField' => __DIR__ .'/SessionSortField.php',
        'Panopto\Session\ArrayOfSessionState' => __DIR__ .'/ArrayOfSessionState.php',
        'Panopto\Session\ListFoldersRequest' => __DIR__ .'/ListFoldersRequest.php',
        'Panopto\Session\FolderSortField' => __DIR__ .'/FolderSortField.php',
        'Panopto\Session\RecorderDownloadUrlResponse' => __DIR__ .'/RecorderDownloadUrlResponse.php',
        'Panopto\Session\Note' => __DIR__ .'/Note.php',
        'Panopto\Session\ListNotesResponse' => __DIR__ .'/ListNotesResponse.php',
        'Panopto\Session\ArrayOfNote' => __DIR__ .'/ArrayOfNote.php',
        'Panopto\Session\ArrayOfguid' => __DIR__ .'/ArrayOfguid.php',
        'Panopto\Session\ArrayOfstring' => __DIR__ .'/ArrayOfstring.php',
        'Panopto\Session\Session' => __DIR__ .'/Session.php',
        'Panopto\Session\ArrayOfSession' => __DIR__ .'/ArrayOfSession.php',
        'Panopto\Session\ArrayOfFolderWithExternalContext' => __DIR__ .'/ArrayOfFolderWithExternalContext.php',
        'Panopto\Session\FolderWithExternalContext' => __DIR__ .'/FolderWithExternalContext.php',
        'Panopto\Session\DateTimeOffset' => __DIR__ .'/DateTimeOffset.php',
        'Panopto\Session\Folder' => __DIR__ .'/Folder.php',
        'Panopto\Session\FolderBase' => __DIR__ .'/FolderBase.php',
        'Panopto\Session\ArrayOfFolder' => __DIR__ .'/ArrayOfFolder.php',
        'Panopto\Session\ListSessionsResponse' => __DIR__ .'/ListSessionsResponse.php',
        'Panopto\Session\ListFoldersResponse' => __DIR__ .'/ListFoldersResponse.php',
        'Panopto\Session\ListFoldersResponseWithExternalContext' => __DIR__ .'/ListFoldersResponseWithExternalContext.php',
        'Panopto\Session\FoldersWithAvailabilitySettings' => __DIR__ .'/FoldersWithAvailabilitySettings.php',
        'Panopto\Session\ArrayOfFolderAvailabilitySettings' => __DIR__ .'/ArrayOfFolderAvailabilitySettings.php',
        'Panopto\Session\FolderAvailabilitySettings' => __DIR__ .'/FolderAvailabilitySettings.php',
        'Panopto\Session\FolderEndSettingType' => __DIR__ .'/FolderEndSettingType.php',
        'Panopto\Session\FolderStartSettingType' => __DIR__ .'/FolderStartSettingType.php',
        'Panopto\Session\SessionsWithAvailabilitySettings' => __DIR__ .'/SessionsWithAvailabilitySettings.php',
        'Panopto\Session\ArrayOfSessionAvailabilitySettings' => __DIR__ .'/ArrayOfSessionAvailabilitySettings.php',
        'Panopto\Session\SessionAvailabilitySettings' => __DIR__ .'/SessionAvailabilitySettings.php',
        'Panopto\Session\SessionEndSettingType' => __DIR__ .'/SessionEndSettingType.php',
        'Panopto\Session\SessionStartSettingType' => __DIR__ .'/SessionStartSettingType.php',
        'Panopto\Session\AddFolder' => __DIR__ .'/AddFolder.php',
        'Panopto\Session\AddFolderResponse' => __DIR__ .'/AddFolderResponse.php',
        'Panopto\Session\AddSession' => __DIR__ .'/AddSession.php',
        'Panopto\Session\AddSessionResponse' => __DIR__ .'/AddSessionResponse.php',
        'Panopto\Session\GetFoldersById' => __DIR__ .'/GetFoldersById.php',
        'Panopto\Session\GetFoldersByIdResponse' => __DIR__ .'/GetFoldersByIdResponse.php',
        'Panopto\Session\GetFoldersWithExternalContextById' => __DIR__ .'/GetFoldersWithExternalContextById.php',
        'Panopto\Session\GetFoldersWithExternalContextByIdResponse' => __DIR__ .'/GetFoldersWithExternalContextByIdResponse.php',
        'Panopto\Session\GetFoldersByExternalId' => __DIR__ .'/GetFoldersByExternalId.php',
        'Panopto\Session\GetFoldersByExternalIdResponse' => __DIR__ .'/GetFoldersByExternalIdResponse.php',
        'Panopto\Session\GetFoldersWithExternalContextByExternalId' => __DIR__ .'/GetFoldersWithExternalContextByExternalId.php',
        'Panopto\Session\GetFoldersWithExternalContextByExternalIdResponse' => __DIR__ .'/GetFoldersWithExternalContextByExternalIdResponse.php',
        'Panopto\Session\GetAllFoldersByExternalId' => __DIR__ .'/GetAllFoldersByExternalId.php',
        'Panopto\Session\GetAllFoldersByExternalIdResponse' => __DIR__ .'/GetAllFoldersByExternalIdResponse.php',
        'Panopto\Session\GetAllFoldersWithExternalContextByExternalId' => __DIR__ .'/GetAllFoldersWithExternalContextByExternalId.php',
        'Panopto\Session\GetAllFoldersWithExternalContextByExternalIdResponse' => __DIR__ .'/GetAllFoldersWithExternalContextByExternalIdResponse.php',
        'Panopto\Session\GetSessionsById' => __DIR__ .'/GetSessionsById.php',
        'Panopto\Session\GetSessionsByIdResponse' => __DIR__ .'/GetSessionsByIdResponse.php',
        'Panopto\Session\GetSessionsByExternalId' => __DIR__ .'/GetSessionsByExternalId.php',
        'Panopto\Session\GetSessionsByExternalIdResponse' => __DIR__ .'/GetSessionsByExternalIdResponse.php',
        'Panopto\Session\GetSessionsList' => __DIR__ .'/GetSessionsList.php',
        'Panopto\Session\GetSessionsListResponse' => __DIR__ .'/GetSessionsListResponse.php',
        'Panopto\Session\GetFoldersList' => __DIR__ .'/GetFoldersList.php',
        'Panopto\Session\GetFoldersListResponse' => __DIR__ .'/GetFoldersListResponse.php',
        'Panopto\Session\GetFoldersWithExternalContextList' => __DIR__ .'/GetFoldersWithExternalContextList.php',
        'Panopto\Session\GetFoldersWithExternalContextListResponse' => __DIR__ .'/GetFoldersWithExternalContextListResponse.php',
        'Panopto\Session\GetCreatorFoldersList' => __DIR__ .'/GetCreatorFoldersList.php',
        'Panopto\Session\GetCreatorFoldersListResponse' => __DIR__ .'/GetCreatorFoldersListResponse.php',
        'Panopto\Session\GetCreatorFoldersWithExternalContextList' => __DIR__ .'/GetCreatorFoldersWithExternalContextList.php',
        'Panopto\Session\GetCreatorFoldersWithExternalContextListResponse' => __DIR__ .'/GetCreatorFoldersWithExternalContextListResponse.php',
        'Panopto\Session\UpdateSessionName' => __DIR__ .'/UpdateSessionName.php',
        'Panopto\Session\UpdateSessionNameResponse' => __DIR__ .'/UpdateSessionNameResponse.php',
        'Panopto\Session\UpdateSessionDescription' => __DIR__ .'/UpdateSessionDescription.php',
        'Panopto\Session\UpdateSessionDescriptionResponse' => __DIR__ .'/UpdateSessionDescriptionResponse.php',
        'Panopto\Session\UpdateSessionIsBroadcast' => __DIR__ .'/UpdateSessionIsBroadcast.php',
        'Panopto\Session\UpdateSessionIsBroadcastResponse' => __DIR__ .'/UpdateSessionIsBroadcastResponse.php',
        'Panopto\Session\UpdateSessionOwner' => __DIR__ .'/UpdateSessionOwner.php',
        'Panopto\Session\UpdateSessionOwnerResponse' => __DIR__ .'/UpdateSessionOwnerResponse.php',
        'Panopto\Session\MoveSessions' => __DIR__ .'/MoveSessions.php',
        'Panopto\Session\MoveSessionsResponse' => __DIR__ .'/MoveSessionsResponse.php',
        'Panopto\Session\UpdateSessionExternalId' => __DIR__ .'/UpdateSessionExternalId.php',
        'Panopto\Session\UpdateSessionExternalIdResponse' => __DIR__ .'/UpdateSessionExternalIdResponse.php',
        'Panopto\Session\UpdateFolderName' => __DIR__ .'/UpdateFolderName.php',
        'Panopto\Session\UpdateFolderNameResponse' => __DIR__ .'/UpdateFolderNameResponse.php',
        'Panopto\Session\UpdateFolderDescription' => __DIR__ .'/UpdateFolderDescription.php',
        'Panopto\Session\UpdateFolderDescriptionResponse' => __DIR__ .'/UpdateFolderDescriptionResponse.php',
        'Panopto\Session\UpdateFolderEnablePodcast' => __DIR__ .'/UpdateFolderEnablePodcast.php',
        'Panopto\Session\UpdateFolderEnablePodcastResponse' => __DIR__ .'/UpdateFolderEnablePodcastResponse.php',
        'Panopto\Session\UpdateFolderAllowPublicNotes' => __DIR__ .'/UpdateFolderAllowPublicNotes.php',
        'Panopto\Session\UpdateFolderAllowPublicNotesResponse' => __DIR__ .'/UpdateFolderAllowPublicNotesResponse.php',
        'Panopto\Session\UpdateFolderAllowSessionDownload' => __DIR__ .'/UpdateFolderAllowSessionDownload.php',
        'Panopto\Session\UpdateFolderAllowSessionDownloadResponse' => __DIR__ .'/UpdateFolderAllowSessionDownloadResponse.php',
        'Panopto\Session\UpdateFolderParent' => __DIR__ .'/UpdateFolderParent.php',
        'Panopto\Session\UpdateFolderParentResponse' => __DIR__ .'/UpdateFolderParentResponse.php',
        'Panopto\Session\UpdateFolderExternalId' => __DIR__ .'/UpdateFolderExternalId.php',
        'Panopto\Session\UpdateFolderExternalIdResponse' => __DIR__ .'/UpdateFolderExternalIdResponse.php',
        'Panopto\Session\UpdateFolderExternalIdWithProvider' => __DIR__ .'/UpdateFolderExternalIdWithProvider.php',
        'Panopto\Session\UpdateFolderExternalIdWithProviderResponse' => __DIR__ .'/UpdateFolderExternalIdWithProviderResponse.php',
        'Panopto\Session\DeleteSessions' => __DIR__ .'/DeleteSessions.php',
        'Panopto\Session\DeleteSessionsResponse' => __DIR__ .'/DeleteSessionsResponse.php',
        'Panopto\Session\DeleteFolders' => __DIR__ .'/DeleteFolders.php',
        'Panopto\Session\DeleteFoldersResponse' => __DIR__ .'/DeleteFoldersResponse.php',
        'Panopto\Session\ProvisionExternalCourse' => __DIR__ .'/ProvisionExternalCourse.php',
        'Panopto\Session\ProvisionExternalCourseResponse' => __DIR__ .'/ProvisionExternalCourseResponse.php',
        'Panopto\Session\SetExternalCourseAccess' => __DIR__ .'/SetExternalCourseAccess.php',
        'Panopto\Session\SetExternalCourseAccessResponse' => __DIR__ .'/SetExternalCourseAccessResponse.php',
        'Panopto\Session\GetRecorderDownloadUrls' => __DIR__ .'/GetRecorderDownloadUrls.php',
        'Panopto\Session\GetRecorderDownloadUrlsResponse' => __DIR__ .'/GetRecorderDownloadUrlsResponse.php',
        'Panopto\Session\CreateNoteByRelativeTime' => __DIR__ .'/CreateNoteByRelativeTime.php',
        'Panopto\Session\CreateNoteByRelativeTimeResponse' => __DIR__ .'/CreateNoteByRelativeTimeResponse.php',
        'Panopto\Session\CreateNoteByAbsoluteTime' => __DIR__ .'/CreateNoteByAbsoluteTime.php',
        'Panopto\Session\CreateNoteByAbsoluteTimeResponse' => __DIR__ .'/CreateNoteByAbsoluteTimeResponse.php',
        'Panopto\Session\EditNote' => __DIR__ .'/EditNote.php',
        'Panopto\Session\EditNoteResponse' => __DIR__ .'/EditNoteResponse.php',
        'Panopto\Session\DeleteNote' => __DIR__ .'/DeleteNote.php',
        'Panopto\Session\DeleteNoteResponse' => __DIR__ .'/DeleteNoteResponse.php',
        'Panopto\Session\GetNote' => __DIR__ .'/GetNote.php',
        'Panopto\Session\GetNoteResponse' => __DIR__ .'/GetNoteResponse.php',
        'Panopto\Session\ListNotes' => __DIR__ .'/ListNotes.php',
        'Panopto\Session\AreUsersNotesPublic' => __DIR__ .'/AreUsersNotesPublic.php',
        'Panopto\Session\AreUsersNotesPublicResponse' => __DIR__ .'/AreUsersNotesPublicResponse.php',
        'Panopto\Session\SetNotesPublic' => __DIR__ .'/SetNotesPublic.php',
        'Panopto\Session\SetNotesPublicResponse' => __DIR__ .'/SetNotesPublicResponse.php',
        'Panopto\Session\IsDropbox' => __DIR__ .'/IsDropbox.php',
        'Panopto\Session\IsDropboxResponse' => __DIR__ .'/IsDropboxResponse.php',
        'Panopto\Session\CreateCaptionByRelativeTime' => __DIR__ .'/CreateCaptionByRelativeTime.php',
        'Panopto\Session\CreateCaptionByRelativeTimeResponse' => __DIR__ .'/CreateCaptionByRelativeTimeResponse.php',
        'Panopto\Session\CreateCaptionByAbsoluteTime' => __DIR__ .'/CreateCaptionByAbsoluteTime.php',
        'Panopto\Session\CreateCaptionByAbsoluteTimeResponse' => __DIR__ .'/CreateCaptionByAbsoluteTimeResponse.php',
        'Panopto\Session\UploadTranscript' => __DIR__ .'/UploadTranscript.php',
        'Panopto\Session\UploadTranscriptResponse' => __DIR__ .'/UploadTranscriptResponse.php',
        'Panopto\Session\GetFoldersAvailabilitySettings' => __DIR__ .'/GetFoldersAvailabilitySettings.php',
        'Panopto\Session\GetFoldersAvailabilitySettingsResponse' => __DIR__ .'/GetFoldersAvailabilitySettingsResponse.php',
        'Panopto\Session\GetSessionsAvailabilitySettings' => __DIR__ .'/GetSessionsAvailabilitySettings.php',
        'Panopto\Session\GetSessionsAvailabilitySettingsResponse' => __DIR__ .'/GetSessionsAvailabilitySettingsResponse.php',
        'Panopto\Session\UpdateFoldersAvailabilityStartSettings' => __DIR__ .'/UpdateFoldersAvailabilityStartSettings.php',
        'Panopto\Session\UpdateFoldersAvailabilityStartSettingsResponse' => __DIR__ .'/UpdateFoldersAvailabilityStartSettingsResponse.php',
        'Panopto\Session\UpdateFoldersAvailabilityEndSettings' => __DIR__ .'/UpdateFoldersAvailabilityEndSettings.php',
        'Panopto\Session\UpdateFoldersAvailabilityEndSettingsResponse' => __DIR__ .'/UpdateFoldersAvailabilityEndSettingsResponse.php',
        'Panopto\Session\UpdateSessionsAvailabilityStartSettings' => __DIR__ .'/UpdateSessionsAvailabilityStartSettings.php',
        'Panopto\Session\UpdateSessionsAvailabilityStartSettingsResponse' => __DIR__ .'/UpdateSessionsAvailabilityStartSettingsResponse.php',
        'Panopto\Session\UpdateSessionsAvailabilityEndSettings' => __DIR__ .'/UpdateSessionsAvailabilityEndSettings.php',
        'Panopto\Session\UpdateSessionsAvailabilityEndSettingsResponse' => __DIR__ .'/UpdateSessionsAvailabilityEndSettingsResponse.php',
        'Panopto\Session\Auth' => __DIR__ .'/Auth.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_6c629975753a482af019f5069dfbfd34');

// Do nothing. The rest is just leftovers from the code generation.
{
}
